### ISSUE TITLE
Poster adding

### ISSUE THREAD

**Issue by LazyGatto** [TomMeHo/vsMetaFileEncoder#1]
As I understood poster cannot be added for now.
Are you planning to add this support in future? =)
Thanks in advance.

**Comment by TomMeHo** [comment]
Hi Lazo,
as of now, it works for me and I have not planned such extensions. The sources I use do not offer any further artwork I could embed into the metafile, so I had not spent any thought on it. But I'd like to understand what you are doing. What's your data source, are you talking about series or movies?
Best regards,
Tom

**Comment by LazyGatto** [comment]
Im using Synology VideoStation to store video lessons for my children too. So there is no information in any online Movie Database on these files. That's why I thought to automatically generate vsmeta files for them. With all needed information, including poster picture. I have separate jpeg files for every lesson I need to store. And manually it is very boring to do =) There is about 600-700 video files.

**Comment by TomMeHo** [comment]
Hi,
I cannot promise too much, but please do the following:
1) Upload a video, generate the vsMeta file and rename it to something like [filename]_initial.vsMeta. To generate the file, you need to trigger an export, I've described it in the readme.
2) Assign a poster and export again.
3) Send me both files for comparison, and please tell me the name of the poster.
I won't be able to respond immediately, but let's see what I can do for you.
Best regards,
Tom
________________________________
Von: Stanislav Vychegzhanin ***@***.***>
Gesendet: Freitag, 9. Juli 2021 10:10
An: TomMeHo/vsMetaFileEncoder ***@***.***>
Cc: Thomas Meder ***@***.***>; Comment ***@***.***>
Betreff: Re: [TomMeHo/vsMetaFileEncoder] Poster adding (#1)


Im using Synology VideoStation to store video lessons for my children too. So there is no information in any online Movie Database on these files. That's why I thought to automatically generate vsmeta files for them. With all needed information, including poster picture.

**Comment by TomMeHo** [comment]
A contributor has added poster support, please try out if it fits your need.
